import React from "react";
import { Container } from "@chakra-ui/react";

import Head from "next/head";

import ItemCard from "../components/ItemCard";
import { Item } from "../interfaces";

import { PrismaClient } from "@prisma/client";

interface IProps {
  items: Item[];
}

const Home = (props: IProps) => {
  const items = props.items;

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={"7xl"} paddingY={"4"}>
        {items.map((item) => (
          <ItemCard Item={item} key={item.id} />
        ))}
      </Container>
    </div>
  );
};

export default Home;

export async function getServerSideProps() {
  const prisma = new PrismaClient();

  const data = await prisma.item.findMany();

  return {
    props: {
      items: data,
    },
  };
}
